### ISSUE TITLE
Podatus rendering problem

### ISSUE THREAD

**Issue by SirPL** [bbloomf/jgabc#11] opened 2016-03-01 18:16 UTC
I'm not sure if it's my computer only, or 'global' problem. Most of podatus' are badly rendered. I deleted all caeciliae fonts I had installed, but the problem still occurs.

![Podatus problem](https://cloud.githubusercontent.com/assets/11311649/13436881/a8457030-dfe1-11e5-9ed0-fb5fbbc0c913.png)

**Comment by bbloomf** [comment] 2016-03-01 18:22
Which browser and Operating System are you using?  This looks like what would happen if it thinks the browser supports font ligatures, but they aren't working correctly most of the time.
You can see it works on my computer:
![image](https://cloud.githubusercontent.com/assets/923595/13437113/8b02b234-dfb0-11e5-9e1e-6451fd96bc60.png)

If I can reproduce the issue here, I should be able to fix it pretty easily.

**Comment by pierrefrancois** [comment] 2016-03-01 18:53
Dear Benjamin and SirPL
      
      I had a similar problem with Firefox (under Linux-Ubuntu). A
      workaround for me is to do it with Chrome (under Linux-Ubuntu) for
      this specific application. Chrome is also much faster in updating
      the score when you modify it.
      
      Kind regards
      
      Pierre
      
      On 03/01/2016 07:22 PM, Benjamin Bloomfield wrote:
    
    
      Which browser and Operating System are you using? This looks
        like what would happen if it thinks the browser supports font
        ligatures, but they aren't working correctly most of the time.
        You can see it works on my computer:
      
      If I can reproduce the issue here, I should be able to fix it
        pretty easily.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SirPL** [comment] 2016-03-01 18:53
I'm using Windows 7 x64, Firefox 44.0.2. I checked other browsers (IE, Chrome, Opera), and there is everything fine.
The funniest thing is, that default "Adoro te" is rendered correctly... Take a closer look at the "Amen" at the end I doubled (the second is added by hand)...
![adorote](https://cloud.githubusercontent.com/assets/11311649/13437830/82f1fea2-dfe6-11e5-934c-1584035cda76.png)

**Comment by bbloomf** [comment] 2016-03-01 19:43
OK, I was just trying it in Firefox, and it does seem that it is the font ligatures acting strangely.  I will try changing it so that it doesn't try to use the ligatures and instead uses a lookup table to find the right unicode characters.  For a better explanation of this, you can look at [the website for the Caeciliae font](http://www.marello.org/projects/caeciliae).  Perhaps it will be better not to use the ligatures anyway.  I will try to get this done some time later this week.  And maybe then, I will look at suppressing the interactive elements when jgabc is not being used to produce an interactive preview of chant.

**Comment by SirPL** [comment] 2016-03-01 20:01
I know gregorio font (I used fontforge to export some of glyphs).
I tried to understand jgabc code and make changes on my own, but without comments it's pretty hard to do.

**Comment by bbloomf** [comment] 2016-03-01 20:04
Yes, sorry about the lack of comments.  I had really only intended it to prove to myself that it could be done, and it did end up getting really complicated and I agree that more comments in the code would probably be helpful, even to me.

**Comment by bbloomf** [comment] 2016-03-02 14:31
OK.  I made the change and it seems to work in Firefox now, so I am closing this issue.

**Closed by bbloomf** 2016-03-02 14:31 UTC
